version: '3.9'

services:
  wpserver:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - customnetwork
  
  mysqlservice:
    image: mysql:latest
    container_name: mysql_dbservice
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=somesecretpassword
      - MYSQL_DATABASE=webdatabase
      - MYSQL_USER=admin
    volumes:
      - '/home/mohit/data/mysqldatabase:/var/lib/mysql'
    networks:
      - customnetwork

networks:
  customnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/28
          gateway: 192.168.200.1
  


  